db:
  name-prefix: prod_
  host: '{cipher}AQCSxdPDq5piP5L1twDV4N8AfTFDQOOrV/WSmzeYIG4f3FvRALwg6Ckt53UV3oVoK0kQ7fiv47He+REMu11PTjK2f/rPPytF4cdyD7mIZTewPO+WnGg3HSdUHbJO+MWqdxy+jgCyhzAFKgV1YAzaDiXkfidY4As/diQb6W6MiENM1BzYzbgzh1YGeGzYRMSRuwg/sKOHAD96EvbM8XwM2X6KOOsBXo28TZ8IfM5JbLErP1TDSbd9MtD001hL1zDA4MNyYi0tG668xUzmkezNJowqvutbBkgUMhfh1kovdktPOHTlbbAUaD9OFqJ55w1YY2+nPWCxlyBRBoIrhxuCLFHFOcOetKc4+yrpHkBrX8Cll/3ec8Ud2hAUxAUJA4M9cBo0gv2DEDJNRcFPYXbF1CrP'
  username: '{cipher}AQCvDZUEzQ2MVvG5pAObu967fDFQdpPCiw0v6BCI6vZuABsjQojFr9RKVjqncQHntXYPe/1v4ocWrt8J3Pi8teHRSA4QSGlyLY9wZrHlva77fBTA6HY+p5ogEfw6fFv3LKJIAcFE6/JwFVxJKwDzVo+QC29LSWQGhAYAIbaUHpHCqGqo34iUb4zEhGf9cbIqTvYyIcopkCTWnaK0iCK8kF5A1e/OGMUPCJUY0K28/sFxYEBoGwYxP3mlj407XvsbsV2CiAe/fi1bwNSornXznlQ+b61N0xiIQbJPsD9ODE0WpsohG3AXUr8QY90oJ7MJyyFaf+YvlgID/R8C1w8Ej10kMRaknwlANaaHLYrhgYU/V7XbSVW/UxNWo1EiCBdNts4='
  password: '{cipher}AQBfmEGTLiGwedTE4Td/R9d7GgK4D0c5uRFGbVc+TDVR8hM+5jALt4P3AsgRU5zlCXLBuvw3anpGbTaEkKCqLh6h+ceCjDqRk4n5R+sJoK5G7AIjp8kVclzCfWbuo7k9tFsvTLucxpQBbU8+kqa7erm7/4xgRxhwpNw1vQ0DbmPqKVXAHqDpDRUb7mHp1mHimrYi94T3PLGVNwOruhnFNC22ZtCenmdRMaorQSuzs+on4jWRgFtIhK6373w9UMYwYHGkOs7mobHetM1o6mYxnsNXk1K/yS3WrQt38q8LrIIvPjbAx6x1wKdSmonqLRTEXFOfj+FBN3PQ7bietlx5cO0ub20THy8iV+Nfn0Db/pe//NpbbsMqsc93eQCWaszYr1U='
  pool-size: 10

sql:
  show: false
  format: false
  ddl-auto: update

spring:
  jpa:
    generate-ddl: true
  redis:
    host: '{cipher}AQBWv7uU1fUSUvzej9JRTzTfsjr/rRYWgygOf4POqVKH2852RBY5mGoznSFvFSwG4hk0JED+ih2UW2/0RsookkNnQmpbDdG53wUizwBNHKSyyoEV/WDEc+HtBmLAU+2gyIhsJuJak4I64AT5BjVu5IHlHZwAwAskR6L2wMX99IYcJRbtJ0LDf90I3uSTfT46nJlaREpAlhLOHLZooW/jhzCD0Ht7lNzn9NnGt43dYayXzZrsMvf/eSTaS3h4sF5BUoLMlTTxlcGj4asELtJxFBPN++gb0UC+RFvSJJYFhvJlLeK8CHYJ1S+2CTOkReguDpLwL+jcYmUm/rFLcgVIpGtnRVJscQl0bl/5TfDSb+85zkdCYW7K1XSfRxTAnFiOXi+FQ9RuIGJW1YufOD90yT4s'
    port: 6379

service:
  scheme: http
  application:
    host: application-be-prod.xquare-prod.svc.cluster.local
  authority:
    host: authority-be-prod.xquare-prod.svc.cluster.local
  point:
    host: point-be-prod.xquare-prod.svc.cluster.local
  user:
    host: user-be-prod.xquare-prod.svc.cluster.local
  timetable:
    host: timetable-be-prod.xquare-prod.svc.cluster.local/timetables
  schedule:
    host: schedule-be-prod.xquare-prod.svc.cluster.local
  git:
    host: git-be-prod.xquare-prod.svc.cluster.local
