db:
  name-prefix: stag_
  host: '{cipher}AQCd3nRV0AIFYGoYmhwWE/ADriEnut0LiRJZ311a0ApXeeDtVzZSo2nszflr79yed5oaGC+zKDHBgNQl20igiRI+GSYJKVjk+6WiKJLdphOU/ukoFSSioF6zqvgSJh46hiZ7wD2rbkRabgwjGnFDvh464Xj4NCCJWaKkET+95iyvzgkBNNR1+VasmJvqK+oIFyh9M6YrFZKvCZnpaYDML8koK/ifxMZVgl06a3gn6Ujb2iS/ysVck0qiVFTgHw3qKMCu3orf2hrKFF7UzpUSA7/r028yIVl250hm6hTYw8jFhfMSYKgL5vK1IVob2FavVPGUpplew+j24yH/k9cTdLliSiJbkZ4Gdo80GEcfmX+xg8RCF531E2QjmFiQjAEB51izdnuAwwOiHGiY6WXQ5hdFZGyl4WDqM7QgOhdWMMsBY938sPP6CRFVlAGVSx8GiQ0='
  username: '{cipher}AQALZXB4hMq967guXu5tXVQPz5BYLwUjT/0eWjkufczR01NfSoQOyvy8M5zh/d5JzyyOq5E+upYh2s+b5VZDjKHb5MHOvgH7uK/gVpSH6kCAGvkGvFbxnSD1DslEqSBqsnFGuUb0P5+UkFHDKhenCyxnSSJJHwpX7+s9d1xYisUoSXLvju8ZDnmlmcNbMwNYXK2tvdWXJmx/RKXgYJFtnuYDVrAhDvwbAeeeWV/Y1deQOJjdKa00Do955EEeYBmvnosW5IQylvpgKbowDcd/t3l5hM0dvEcY9cpCCVrrWYaMLR84pgtKiDn2Dl1QzmUe/cimNQtegvzxspWRv2vqhV1vvxF9e25TFBINdVKK0PsEistw17NJIC2lJ23QoI3BmVk='
  password: '{cipher}AQC2lg0fib9/9qK5PkHhhvyVJfntvkeoqvMjmCSUcRyfdjJRkCffBHPIMRlcVAsvLUvg3fB+xBxLcp/IjRAqo1S+yiTTh2xAbMBgg60CckDNQ+3v/z810T6AryllYcvXWGwEnD9JndI58CK+NtmmN4O9KXcBFePN5m/Le5OYdw+Zda9jYD6I9FX08TWo34Gso+v7/vZdw2G5viC2ECiY6FZIRgHTBGG6JZ7VN1+xbHAIOcuyr31XmOffGKX1sroWEHfhLEbd39O6Qgj/c22bEoMhMoEBybZ0oaGvCYL+LOVWWL419IJLJwvYteubTD/fYx89vOvjdbbBJofdjsm7aRfy+ywWkH9tq5pykyOj/OUqKXTPyGJP0laOiUGA/dwq0Cw='
  pool-size: 5

sql:
  show: true
  format: true
  ddl-auto: validate

spring:
  jpa:
    generate-ddl: true
  redis:
    host: localhost
    port: 6379
