db:
  name-prefix: stag_
  host: '{cipher}AQC7XtpYtdtY3brsqaILeqydP06lGoyTV25u1bXLB90Z20tXbKxxV5e9yy5WjzlBYy9jNIvWbUgpfgHxZImLgX7uqP9iZfQHDoh+uIY8axTnTJlysTFkhhgahM6Frj+doakGLHHomIXyGrT6grsgSDL3aaHStsLgxI+DjS/qxKYXrRBKZEmfiQWSRB+vckH2UflYjbBcpnW169NxrM5yutsEB//y8oJODpMzv7e79hDkDOQViuh6F4tHIf/z2mTVjhfw7eh+mb0SqRCNRIys0aIVXTtKLYejzV57g8WGfxWXIrSWsu0EIZp7F8/qSwIMtcYcwv+2UDsSUPsVdz7W5THIDaFImh3fWqx25PdZjx1naiIcfdHPgfDWwbpiPN5rgmKCXyBgrPUojThbNTyeCeCl'
  username: '{cipher}AQALZXB4hMq967guXu5tXVQPz5BYLwUjT/0eWjkufczR01NfSoQOyvy8M5zh/d5JzyyOq5E+upYh2s+b5VZDjKHb5MHOvgH7uK/gVpSH6kCAGvkGvFbxnSD1DslEqSBqsnFGuUb0P5+UkFHDKhenCyxnSSJJHwpX7+s9d1xYisUoSXLvju8ZDnmlmcNbMwNYXK2tvdWXJmx/RKXgYJFtnuYDVrAhDvwbAeeeWV/Y1deQOJjdKa00Do955EEeYBmvnosW5IQylvpgKbowDcd/t3l5hM0dvEcY9cpCCVrrWYaMLR84pgtKiDn2Dl1QzmUe/cimNQtegvzxspWRv2vqhV1vvxF9e25TFBINdVKK0PsEistw17NJIC2lJ23QoI3BmVk='
  password: '{cipher}AQC2lg0fib9/9qK5PkHhhvyVJfntvkeoqvMjmCSUcRyfdjJRkCffBHPIMRlcVAsvLUvg3fB+xBxLcp/IjRAqo1S+yiTTh2xAbMBgg60CckDNQ+3v/z810T6AryllYcvXWGwEnD9JndI58CK+NtmmN4O9KXcBFePN5m/Le5OYdw+Zda9jYD6I9FX08TWo34Gso+v7/vZdw2G5viC2ECiY6FZIRgHTBGG6JZ7VN1+xbHAIOcuyr31XmOffGKX1sroWEHfhLEbd39O6Qgj/c22bEoMhMoEBybZ0oaGvCYL+LOVWWL419IJLJwvYteubTD/fYx89vOvjdbbBJofdjsm7aRfy+ywWkH9tq5pykyOj/OUqKXTPyGJP0laOiUGA/dwq0Cw='
  pool-size: 5

sql:
  show: true
  format: true
  ddl-auto: validate

spring:
  jpa:
    generate-ddl: true
  redis:
    host: localhost
    port: 6379
