db:
  name: '${db.name-prefix}application'

# SQS
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: '{cipher}AQBhun52tN1x0q7e4AqjMoMX21xz2dqErRodOnVbKnZ4DEs+W7HuJYeTeaywf2l/JbDt0RJZVJXBMQODe0o98THUrZaaKCfSDecdAWs1GxvwNP3qnWKas7CIKs4GepFHjbxV+OQfo2sr9CrVg0sAA9zeiLjyjfyztOB9JANClOjxeAKY0DgR40qbA9/bveFIvBRaFa0JUb/6ug6jUKJdnb5m9TQZK2aVFofv92THuAirfinR/I1D0reLI5qawsrDbEzIH1I7UuYk+0846ifxfn5Y17jf7/6Dr4GYKe/q4EqmMT5bGU+AxUVAEkzlVvlHxKKnkph52/rCy6LaPygqCqMG9nnWQbulkJZqAPjfDOcyJRFx9VYQcfeOKVdPBVqLUtNixrEwyH0iYt5bTtOuLsqK'
      secret-key: '{cipher}AQAtkCUoF4JgISnC9AG8F2eDEFNccopyPUqUqWLXLqeEP05iXEZbewDld0jMjCmi0huJ4qg5Y/NjZTXVLtpJEBCeOjJk2ZdiMTM6xcweVxqfwzilw/NUh91WslWmAV1ZDRA51pY23t32pcqLhZiyqNTcur+sdF3wtWx6luRQQvrexzc6cbWZMPHn3nYbil28DoMc1b2gXV9RdZzdRiDHIUZCsfl+DNdROMTYahcdV6mfZJwdKGIUg4M8XmNU5Fz8H74xoH3orNN5SmfFPyz8YcZcK+eW/pD2u6QZGEGUlrjCWkMdtC73BwF/YhB1ZKmMZy5hxjeB0CVBqp677ALOGUUI2BmiX4zcZpZ433RDZlvOJjXPheOBh2MAUWE3qywJOjVQUj1Atl98cvURty1/ceuo83oFG0/WkHY3vh/i3LkztQ=='

sentry:
  dsn: '{cipher}AQB7QqOsSk4/LfIA70fIBxGpHftpEp2+yVPxDVp9qSxGKdtMRi0PnEVJQbaVCI4Cy91zMhyfI4TBuAbpVagS1jE0+XJrnNdMMokRmOAyZzTwLgw2cTw/iDiwPhiZCh9NaFgCkwe0N+ctLNnM470fjPeKLOpd+O55SRvrBqIGzkpX43+Rah1K8N2ObodeGxZ/F325kUphPQQFAdHWYRwezkV+MSZrTmjIB5TicMAsRWNNaf1+1ahaWMC6vAuwWgGN+DnH2rKThdPnqDwY6doMZ++3FrNT3lQIjsg1+dSgIe2vBRU2m+LSvgjFcbjs6mGFjkOcGFFjJTWTTIo5g9AdYMVxEQCEKjLuxTBuKqa8ZsTh+wmg97PsOvigWH1eci9K7xqx6jY09dmf/mPab5nmJlVU4yG8wCfUxXF6flcx6AVsWEF+FI48FiZ/6LKWXpHTUapovfGlGLoIyxCNnwzyEU2J'