db:
  name: '${db.name-prefix}feed'

# SQS
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: '{cipher}AQBtPp6OEhCTjwagpZ1zmc80mbKqGRuVRMSrxrox1moZLlM6Cm/wW746HezDArp0PCpKWjyqr77hV1DIBj3zGJY9o9K2vuzo9IhYYYFHJJNfQt3vIODiszUoGppbfEBYKQTBnTWJKtGm32HMeYk3biAIXXUMDYcGZiPpdE7yaIC6CKQ/Ss5cbMSyKgTI+Tbp6t+8S1oFexCeRy/doIIrr+02PFnV99ynY/zbq9VGdDYYADg2d6coZ5j+iXbp47lXkRDtKjkNvo9hRARpXiz3dfXC6wM0Py0pKMHpFE9O/LWSK6y2MW3nzrE3HuzIdHQRkDB2QPtzP8dYU5FXotzgmUCGzLAgVOWemcbOzjnbzPu4kml8lxHdPJNTkRm8GSjf8Uqjkd5U8wiXLiR4YLKTQyna'
      secret-key: '{cipher}AQCEaeCZGnbeiOK2dLjfyM4rmT0m7lWitcJYewY7ugF80kv02wKCe/IBU96m/LlR4Fau/AW+3KF2jD20gvJvyVjLqkElUe4D2v9Eut6ABieyopp29fYqF765LQJ16nnc1ZRqN+Vhqtjc8//e8osVa+BrDZbQJXLh3Qk48vAu9rKiKrIj5jzTMKtSSeSBDv+yx+TVZ0wZSg7BaO+UNo7W6ZCCKbaoNdpDfx8DjP0kStDyBOOKgHehMq2sEN6RYqP8G21AFT6TCGa6aadM0BkcdoyH1f4Swbh/QVOrxRv8AZf+DCRiAXH9w+x2fgLTvxNflz3kpvYP+HAkS1FkwQwy8uVQxeErCkMTzUqnI52dOQ18R26ncmY093nAaAljE6BCzCk7rVSj9vJJ6GiHvRdb1JHiyw0MJvjoH91VrLX5NjZmeQ=='

webhook:
  url: '{cipher}AQAODuEPrT7LrE4LHNOfjjUcjtoCzMF0Zh0mE9nsfSFsZSAIf5mHUPLpGyemrK7LgU6uzXpd+sbKnc0Yn9WRW7k9mNtKgFjph/KnMzvtzhnGBrnoMS+qsI24Ym/tBVFRppgJOzH02tGLR+KhyhREGcvLY7pTEq1QFw4vXo6OR+5bGaFqsdnMZD1QnER7DkqTs0nFhsoEKIMexwTtHPHaXPaVnrZO9BcY31PG6aNuxTIZtMvUowpydJce2TqIp3hjU29FvP6DDWJx1MHIpefgXxQKcOdifdSFclKCXFIBmkAEgSW9k0xtrlr4AcSYlgqz3cT6w17C48KdVfgfGX7wCHC5WMXnDQpZj3qXvM98eJ+LxaforjAIUgNYLSYPl+YmyCx5ObewSXggKGb46djYD+iZK7ZkDfw/ZhFv6x6pS4IVLviJIKRfc8KCyx/BO0L+qz0nGhstQQ0t3gbGpLEUU81fpojUC7w/tRICpEmmNyj1cw=='
