db:
  name: '${db.name-prefix}point'

# SQS
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: '{cipher}AQAzErW2E6eBl5AOFz68zSZYWPCfwGEZkE0QjrYKwrC+CPx0xD0FW3ApnTbnEL/v3jglTNcfkQNPpTLC+g0hz7yRG+C/EYw2NZI7kUhbQQ/xE0XXGH6njHafDMV1+3URnHV5McLzTQvkX69mqBZ4o3eu+p6NIWSuAPhRaiTVUbY0yRB4yUnlz8JeMAhIkdF6G2EnwfqaHIfmaQ5fYJzRRiiUY2spZTYxqwrBsVibtRTItjb4Ow0+GAy6jO6QiwkHGyiCRT8Y2rwSStpWcnF6RsiVLvj4JS7dHmCXmgOXSRpU6cBGvoDCG/XabNHPI61B3/ZfH/0pGLoz2/BPXMj4dszESM5X6gsyMfQ38wzTX8X10amlVQEhgYESJd3ohQZTjsexChgB6vvfLmmx8+U2ERCB'
      secret-key: '{cipher}AQA//fksew9ooyYNCf5wTn75hH72iwFtTIwsk3vV5iE9wtSb0g4NckOAPRIFRajCXshWaUQ2WN6pv+T0VNuOXsTguBRiesVW4c8oEvCWCv5iLRLLsuYCVwKqVl2BAaleWshRer/gi6SBncL4kvJ0KhCLcBYqL5JBvTWBGS93MbSr4fjSm85jPIR+02BFrwtdqdqC4kzx4llorwgSvnfAZBybEgUpyn/BeloN0SYHo6bdVWDjXOlQUQHscw7yosijnT2a26eEKbNg/u4vTALyrCKn4BQ/mQCTu1jW2xl1V3dsrjHf1WwL0S+sSdyTVt8iHGvzAmQV8vFCJeQno3BeFJiVes+g5Us6QMcr/lPYLsYvNZYs/aSmC49TQVUzpTAIOJiqRjZhIQv3G9li9YYl4D7ss2bfgw2QaKc+ZakVb5KkTw=='

sentry:
  dsn: '{cipher}AQB+0l7D7sCWQQMagGqsiM5HSuZT6+hgXUo5PdC8yA8fTquE4FzepLehZNcJIrEONpgkb+zembSKBuqFrwFCc/ar08WBsRLK7bf0l1B6L7cHbnztGKso/kltflSFR2xSUpsiq4L1Egm6QMu9GJtTfXJy4Hm/F7uO5m5Y0GK7lyhJKOuUOFS3/lFltcWgu3tIUBkOrUWtC1KmL/nuCx9YWT6KcO2n76q+rb5D2ChDd1RbJf1DwylmZQhLSUIzn6okqEYid2xoCcHZeKTRVw9xI/NlUU0yak2rW3ZxRVbsl5p0+4xi1s25oVQQp1IYqGMTHkNQIOcXBjaAumxrkMniw+iEnWLcufN8wT9oxvFZDw8DHrhVXOdYYtn9eAyB23xsh7cUikfBHxRmNopzFs/0jXrJv5+HLMZSLqistY3cDZhvY9N1s6VbcGkK+wcvOi79fILhTd7E2t8WK76vZjGo2kvf9lMDbqthp3/LzeJw7ojhFA=='
  traces-sample-rate: 1.0