db:
  name: '${db.name-prefix}pick'

sentry:
  dsn: '{cipher}AQBYZaXEgqR0apzK4hycpJeYsiifdjDhfhahmnLJ6JdzGBILbcD22McYUinthtY0bLEZnMz1L5rFomWF+2fQAshaJ5qsIFIXZ9Kf+UqpZQUzy2THq4J3b246+U8vMEnIG1xAcgoz44gH5bMQHiRjWT/60xS6m9WKZKYtVuem1t6LJFsLg3ZKD5FUDkQ5LhgcmmZi06HTMPhT6nKPde8YVQHvavMFBUQ3TKwV3LSOJxEynFSpV5YQBmdB1ASvvf5nSvddXprjNRk4RfasZ/UjhpNadXYf8tkg3i8nqWwyWZkSZrKlMGImONSCY4X0+rDeoslnyRDuXhi61OnhHsO3KyLaeVRDQ75/DNWJnx6vYb7eOLzpRupFCmt8ykuQWNGG7a6tYSyE2LvNkfYC0Re8Gtj2mYTfV0vjwru/jQrgEceRlbRyrwP0rLf73nzttaE+Hc2r87rzqvduqt8vy8B+WPKgHrS4gHYhaCcKSJ2050U71w=='