db:
  name: '${db.name-prefix}user'

jwt:
  secretKey: '{cipher}AQAuh/AOpNTNzFJGrVjPoYwFePK8qzt+czy1OZDAp6unfbHW4swMTUxOpbsqXXT2tc4KieMxqGnncMBye1XEm8zyfzr83pqnjX5Zt0L5Kj1tCyHm31kx21y5aLTIwDAPy20P3SRASv8ZkQBwdMbd9F2koI6TbvkHb/F5XulYakePef+fgXtQ2erOeVTBfa1oBS5mtD4tuYFP0+YWMiuT+xT31JRopNYYzyvFHPKnGI8fkm/yQLYAxN2VOtId6rK3UXbCwIxjYDJnXSs/xts4TugkRLiMMKgwY05BJe+mb3to8955QoGiylAHVx5SQRdn8dWZq/3dC9kirammL5cS7C8d7iF8i7RYqTus7zUgxNrTMpoEwUewzuaLSw4eIvCUh1QgjZ5A8P6PhlaGZo0QM/51zaQEYGkkCVxaoYMjlx0RojWEgR1680w0hj3E5F+AecsRQcQfWFYCSsMri2NkBsF3'
  refreshTokenProperties:
    expirationAsHour: 120
  accessTokenProperties:
    expirationAsHour: 2
    
security:
  value: '{cipher}AQAgnj2Igm/imdP98rs4nfYDfE8GPzep859OdIt3QbFyuMtVitq9IT6EZW83cvRi8GKOI4uZrHYEKvV5LkrLwsHROj4XPUt/v5QYB98FHuS8VTB7wDK+nKrT/FRgqDfCBoojIyDqQmwSZG1uObFD7UFfiFblovgxlRGxOmbRWCPb5DFs6TUSgGlz+tM99LxxH9SfDIVAoiY1jGQ49ukzuUveRRSP5q+Fnj9J+oXRpAhVJqhkl/I7lEibzTwOklyXiO2Ig6tggY1Rp5hgwXU6i6XfNCLE5yxqLyYi5D80iZBw4KiPdCm7u9EJZ0zkzNKMPRrgDSEk445esooWUgFE857sGhZFc14fo8EKkblblmrRiGVw+guAu4PRheigt6MIdYrKm8WkZlAsEuHsY5tSoWaz'
